server:
  port: 8084
  servlet:
    context-path: /gic-task/v1
spring:
  application:
    name: GICTask
  datasource:
    url: jdbc:mysql://localhost:3306/gic?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: somerandompassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect